projeto_vagas/app_usuar/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("cadastro/", views.cadastro, name="cadastro"),
    path("logout/", views.logout_view, name="logout_view"),
]

projeto_vagas/projeto_vagas/urls.py
from django.contrib import admin
from django.urls import path, include
from app_vagas import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("auth/", include("app_usuar.urls")),
    path("home/", include("app_vagas.urls")),
]

projeto_vagas/app_vagas/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

FAIXA_SALARIAL_CHOICES = [
    (1, "Até 1.000"),
    (2, "De 1.000 a 2.000"),
    (3, "De 2.000 a 3.000"),
    (4, "Acima de 3.000"),
]

ESCOLARIDADE_CHOICES = [
    (1, "Ensino Fundamental"),
    (2, "Ensino Médio"),
    (3, "Tecnólogo"),
    (4, "Ensino Superior"),
    (5, "Pós / MBA / Mestrado"),
    (6, "Doutorado"),
]


class Empresa(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_empresa = models.CharField(max_length=100)

    def __str__(self):
        return self.nome_empresa


class Candidato(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_candidato = models.CharField(max_length=100)
    faixa_salarial = models.IntegerField(choices=FAIXA_SALARIAL_CHOICES)
    escolaridade_minima = models.IntegerField(choices=ESCOLARIDADE_CHOICES)

    

    def __str__(self):
        return self.nome_candidato


class Vagas(models.Model):
    nome = models.CharField(max_length=100)
    faixa_salarial = models.IntegerField(choices=FAIXA_SALARIAL_CHOICES)
    escolaridade_minima = models.IntegerField(choices=ESCOLARIDADE_CHOICES)
    requisitos = models.TextField()
    empresa = models.ForeignKey(Empresa, related_name="vagas", on_delete=models.CASCADE)
    data_criacao = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        super(Vagas, self).save(*args, **kwargs)
        candidatos_aplicados = Vagas_aplicadas.objects.filter(vaga=self)
        for candidato_aplicado in candidatos_aplicados:
            candidato = candidato_aplicado.candidato
            pontuacao = 0

            if int(self.faixa_salarial) >= candidato.faixa_salarial:
                pontuacao += 1

            if candidato.escolaridade_minima >= int(self.escolaridade_minima):
                pontuacao += 1

            candidato_aplicado.pontuacao = pontuacao
            candidato_aplicado.save()


class Vagas_aplicadas(models.Model):
    candidato = models.ForeignKey(Candidato, on_delete=models.CASCADE)
    vaga = models.ForeignKey(
        Vagas, related_name="vagas_aplicadas", on_delete=models.CASCADE
    )
    pontuacao = models.IntegerField(default=0)
    data_criacao = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.candidato.nome_candidato} - {self.vaga.nome}"

projeto_vagas/projeto_vagas/templates/cad_vagas.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Cadastro de Vaga</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cad_vagas.css' %}">
</head>
<body>
    <div class="container">
        <h1>Cadastro de Vaga</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="nome">Nome da Vaga:</label>
                <input type="text" id="nome" name="nome" required>
            </div>
            <div class="form-group">
                <label for="faixa_salarial">Faixa Salarial:</label>
                <select id="faixa_salarial" name="faixa_salarial" required>
                    {% for choice in faixa_salarial_choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="escolaridade_minima">Escolaridade Mínima:</label>
                <select id="escolaridade_minima" name="escolaridade_minima" required>
                    {% for choice in escolaridade_choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="requisitos">Requisitos:</label>
                <textarea id="requisitos" name="requisitos" required></textarea>
            </div>
            <div class="form-group">
                <button type="submit">Cadastrar Vaga</button>
            </div>
        </form>
        {%if vagas%}
        <a href="{% url 'vagas_cadastradas' %} " class = 'form-group'>
            <button>Voltar</button>
        </a>
        <br>
        {%else%}
        <a href="{% url 'logout_view' %}" class = 'form-group'>
            <button>Sair</button>
        </a>
        {%endif%}
    </div>
</body>
</html>

projeto_vagas/projeto_vagas/templates/cadastro.html
<!DOCTYPE html>
{% load static %}
<html>


<head>
    <title>Cadastro</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/cadastro.css' %}">
</head>
<body>
    <div class="container">
        <h1>Cadastro</h1>
        {% if aviso %}
        <p class="aviso" id="aviso">{{ aviso }}</p>
        {% endif %}
        <div class="form">
            <div class="toggle">
                <button id="candidatoBtn" onclick="toggleForm('candidato')">Candidato</button>
                <button id="empresaBtn" onclick="toggleForm('empresa')">Empresa</button>
            </div>
            <form id="candidatoForm" class="cadastro-form" action = "{% url 'cadastro' %}" method="POST">
                {% csrf_token %}
            
                <label for="email">E-mail:</label>
                <input type="email" id="email" name="email" required>

                <label for="nome">Nome:</label>
                <input type="text" id="nome" name="first_name" required>

                <label for="sobrenome">Sobrenome:</label>
                <input type="text" id="sobrenome" name="last_name" required>

                <label for="senha">Senha:</label>
                <input type="password" id="senha" name="password" required>

                <label for="faixa_salarial">Faixa Salarial:</label>
                <select id="faixa_salarial" name="faixa_salarial" required>
                    <option value="" disabled selected>Selecione a faixa salarial</option>
                    {% for choice in faixa_salarial_choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>

                <label for="escolaridade_minima">Escolaridade Mínima:</label>
                <select id="escolaridade_minima" name="escolaridade_minima" required>
                    <option value="" disabled selected>Selecione a escolaridade mínima</option>
                    {% for choice in escolaridade_choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
                <button type="submit">Cadastrar Candidato</button>
            </form>

            <form id="empresaForm" class="cadastro-form" action = "{% url 'cadastro' %}" method="POST">
                {% csrf_token %}

                <label for="email">E-mail:</label>
                <input type="email" id="email" name="email" required>

                <label for="senha">Senha:</label>
                <input type="password" id="senha" name="password" required>

                <label for="nome_empresa">Nome da Empresa:</label>
                <input type="text" id="nome_empresa" name="nome_empresa" required>

                <button type="submit">Cadastrar Empresa</button>
            </form>
            <a href="{% url 'login' %}">
                <button id = 'a'>Voltar</button>
            </a>
        </div>
    </div>

    <script>
        const errorMessage = document.getElementById('aviso');

        if (errorMessage) {
            setTimeout(() => {
                errorMessage.style.display = 'none';
            }, 5000);
            errorMessage.style.color = 'red';
        }

        function toggleForm(formType) {
            const candidatoForm = document.getElementById("candidatoForm");
            const empresaForm = document.getElementById("empresaForm");
            const candidatoBtn = document.getElementById("candidatoBtn");
            const empresaBtn = document.getElementById("empresaBtn");


            if (formType === "candidato") {
                candidatoForm.style.display = "block";
                empresaForm.style.display = "none";
                candidatoBtn.disabled = true;
                empresaBtn.disabled = false;
            } else if (formType === "empresa") {
                candidatoForm.style.display = "none";
                empresaForm.style.display = "block";
                candidatoBtn.disabled = false;
                empresaBtn.disabled = true;
            }
        }
    </script>
</body>
</html>

projeto_vagas/projeto_vagas/templates/dashboards.html
<!DOCTYPE html>

{%load static%}
<html>
<head>
    <title>Dashboard</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboards.css' %}">
</head>
<body>
    <div class="container">
        <h1>Dashboard</h1>
        <div class="chart-container">
            <canvas id="vagasChart"></canvas>
        </div>
        <div class="chart-container">
            <canvas id="candidaturasChart"></canvas>
        </div>
        <div class="back-button">
            <a href="{% url 'vagas_cadastradas' %}">Voltar para Vagas Cadastradas</a>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        const vagasData = {
            labels: ['Mes atual'],
            datasets: [{
                barPercentage: 2,
                barThickness: 250,
                label: 'Vagas Criadas',
                data: [{{ vagas_criadas }}],
                backgroundColor: 'rgba(220, 53, 69, 0.8)',
                borderColor: 'rgba(220, 53, 69, 1)',
                borderWidth: 1
            }]
        };

        const candidaturasData = {
            labels: ['Mes atual'],
            datasets: [{
                barThickness: 250,
                label: 'Candidaturas Recebidas',
                data: [{{ candidaturas_recebidas }}],
                backgroundColor: 'rgba(0, 123, 255, 0.8)',
                borderColor: 'rgba(0, 123, 255, 1)',
                borderWidth: 1
            }]
        };

        const chartOptions = {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                y: {
                    beginAtZero: true,
                    grace:'5%',
                    ticks:{
                        stepSize:2
                    }
                }
            }
        };

        const vagasChartCanvas = document.getElementById('vagasChart').getContext('2d');
        new Chart(vagasChartCanvas, {
            type: 'bar',
            data: vagasData,
            options: chartOptions
        });


        const candidaturasChartCanvas = document.getElementById('candidaturasChart').getContext('2d');
        new Chart(candidaturasChartCanvas, {
            type: 'bar',
            data: candidaturasData,
            options: chartOptions
        });
    </script>
</body>
</html>

projeto_vagas/projeto_vagas/templates/detalhes_vaga.html
<!DOCTYPE html>
{%load static%}
<html>
<head>
    <title>Detalhes da Vaga</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/detalhes_vaga.css' %}">
</head>
<body>
    <div class="container">
        <h1>Detalhes da Vaga: {{ vaga.nome }}</h1>
        <p>Salário: {{ vaga.get_faixa_salarial_display }}</p>
        <p>Escolaridade Mínima: {{ vaga.get_escolaridade_minima_display}}</p>
        <div class="aplica_vaga">
        <a href="{% url 'aplica_vaga' vaga.id %}">
            <button>Candidatar-se</button>
        </a>
        </div>
        
        <h2>Candidatos Interessados</h2>
        <div class="candidatos">
            {% for candidato in candidatos %}
            <div class="candidato">
                <h3>{{ candidato.nome_candidato }}</h3>
                <p>Faixa Salarial Desejada: {{ candidato.get_faixa_salarial_display }}</p>
                <p>Escolaridade Mínima: {{ candidato.get_escolaridade_minima_display }}</p>
            </div>
            {% endfor %}

        </div>
        {% if mensagem %}
            <p>{{ mensagem }}</p>
            {% if pontuacao is not None %}
                <p>Pontuação: {{ pontuacao }}</p>
            {% endif %}
        {% endif %}
        
        <a href="{% url 'vagas' %}">
            <button>Voltar</button>
        </a>
    </div>
    
</body>
</html>

projeto_vagas/projeto_vagas/templates/detalhes_vaga_empresas.html
<!DOCTYPE html>
{%load static%}
<html>
<head>
    <title>Detalhes da Vaga</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/detalhes_vaga.css' %}">
</head>
<body>
    <div class="container">
        {% if aviso %}
        <p class="aviso" id="aviso">{{ aviso }}</p>  
        {% endif %}
        <h1>Detalhes da Vaga: {{ vaga.nome }}</h1>
        <p>Salário: {{ vaga.get_faixa_salarial_display }}</p>
        <p>Escolaridade Mínima: {{ vaga.get_escolaridade_minima_display}}</p>
        
        <h2>Candidatos Interessados</h2>
        <div class="candidatos">
            {% for candidato in candidatos %}
            <div class="candidato">
                <h3>{{ candidato.nome_candidato }}</h3>
                <p>Faixa Salarial Desejada: {{ candidato.get_faixa_salarial_display }}</p>
                <p>Escolaridade Mínima: {{ candidato.get_escolaridade_minima_display }}</p>
                <p>Email: {{ candidato.user.email }}</p>
                <p>Pontuação: {{ candidato.pontuacao }}</p>
            </div>
            {% endfor %}
        </div>
        <a href="{% url 'edita_vaga' vaga.id %}">
            <button>Editar vaga</button>
        </a>

        <a href="{% url 'vagas_cadastradas' %}">
            <button>Voltar</button>
        </a>
    </div>
    
</body>
</html>

projeto_vagas/projeto_vagas/templates/edita_vaga.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <title>Editar Vaga</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cad_vagas.css' %}">
</head>
<body>
    <div class="container">
        {% if aviso %}
        <p class="aviso" id="aviso">{{ aviso }}</p>  
        {% endif %}
        <h1>Editar Vaga: {{ vaga.nome }}</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="nome">Nome da Vaga:</label>
                <input type="text" id="nome" name="nome" value="{{ vaga.nome }}">
            </div>
            <div class="form-group">
                <label for="faixa_salarial">Faixa Salarial:</label>
                <select id="faixa_salarial" name="faixa_salarial">
                    {% for choice in faixa_salarial_choices %}
                    <option value="{{ choice.0 }}" {% if choice.0 == vaga.faixa_salarial %}selected{% endif %}>{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="escolaridade_minima">Escolaridade Mínima:</label>
                <select id="escolaridade_minima" name="escolaridade_minima">
                    {% for choice in escolaridade_choices %}
                    <option value="{{ choice.0 }}" {% if choice.0 == vaga.escolaridade_minima %}selected{% endif %}>{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="requisitos">Requisitos:</label>
                <textarea id="requisitos" name="requisitos">{{ vaga.requisitos }}</textarea>
            </div>
            <a href="{% url 'deleta_vaga' vaga.id %}" class="voltar-link">Excluir Vaga</a>
            <br>
            <button type="submit">Salvar Alterações</button>
            <br>
            <a href="{% url 'detalhes_vaga_empresas' vaga.id %}" class="voltar-link">Voltar</a>  
        </form>
    </div>
</body>
</html>

projeto_vagas/projeto_vagas/templates/home.html
{% load static %}

<!DOCTYPE html>

{% load static %}
<html>
<head>
    <title>Página Inicial</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
</head>
<body>
    <div class="container">
        <h1>Bem-vindo ao Sistema de Vagas</h1>
        <div class="buttons">
            <a class="login-button" href="{% url 'login' %}">Login</a>
            <a class="vagas-button" href="{% url 'vagas' %}">Vagas Cadastradas</a>
        </div>
    </div>
</body>
</html>

projeto_vagas/projeto_vagas/templates/login.html
<!DOCTYPE html>
{%load static%}
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
    <div class="container">
        <h1>Login</h1>
        {% if error_message %}
        <p class="error-message" id="error-message">{{ error_message }}</p>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <label for="username">Email:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Senha:</label>
            <input type="password" id="password" name="password" required>

            <button type="submit">Entrar</button>
            <br>
            <br>
        </form>

        <a href="{% url 'cadastro' %}">
            <button>Criar conta</button>
        </a>
        <a href="{% url 'home' %}">
            <button>Pagina Inicial</button>
        </a>
    </div>

    <script>
        const errorMessage = document.getElementById('error-message');

        if (errorMessage) {
            setTimeout(() => {
                errorMessage.style.display = 'none';
            }, 5000);
            errorMessage.style.color = 'red';
        }
    </script>
</body>
</html>

projeto_vagas/projeto_vagas/templates/vagas.html
<!DOCTYPE html>
{%load static%}
<html>
<head>
    <title>Vagas Disponíveis</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/vagas.css' %}">
</head>
<body>
    <div class="container">
        <h1>Vagas Disponíveis</h1>
        <div class="vagas">
            {%if vaga == None%}
            <p>{{aviso}}</p>
            {%endif%}
            {% for vaga in vagas %}
            <div class="vaga">
                <h2>{{ vaga.nome }}</h2>
                <p>Salário: {{ vaga.get_faixa_salarial_display }}</p>
                <p>Escolaridade Mínima: {{ vaga.get_escolaridade_minima_display}}</p>
                <a href="{% url 'detalhes_vaga' vaga.id %}">
                    <button>Ver detalhes</button>
                </a>
            </div>
            {% endfor %}
            {%if mensagem%}
            <p>{{mensagem}}</p>
            {% endif %}
        </div>
        <div class="logout-button">
            <a href="{% url 'logout_view' %}">
                <button>Sair</button>
            </a>
        </div>
        
    </div>    
</body>
</html>

projeto_vagas/projeto_vagas/templates/vagas_cadastradas.html
<!DOCTYPE html>
{%load static%}
<html>
<head>
    <title>Vagas Cadastradas</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/vagas_cadastradas.css' %}">
</head>
<body>
    <div class="container">
        {% if aviso %}
        <p class="aviso" id="aviso">{{ aviso }}</p>  
        {% endif %}
        <h1>Vagas Cadastradas</h1>
        <div class="vagas">
            {% for vaga in vagas %}
            <div class="vaga">
                <h2>{{ vaga.nome }}</h2>
                <p>Salário: {{ vaga.get_faixa_salarial_display }}</p>
                <p>Escolaridade Mínima: {{ vaga.get_escolaridade_minima_display}}</p>
                <a href="{% url 'detalhes_vaga_empresas' vaga.id %}">
                    <button>Ver detalhes</button>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="logout-button">
            <a href="{% url 'logout_view' %}">
                <button>Sair</button>
            </a>
        </div>
        <div class="cadastro_vaga-button">
            <a href="{% url 'cad_vagas' %}">
                <button>Cadastrar nova vaga</button>
            </a>
        </div>
        <div class="logout-button">
            <a href="{% url 'dashboards' %}">
                <button>Gráficos de desempenho</button>
            </a>
        </div>
    </div>    
</body>
</html>